INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlState`, `mdlClass`) VALUES ('Acceso', '', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Accesos', 'Manejo de Accesos', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Tipo', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Tipos', 'Roles de Usuarios', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Categoria', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Categorias', ' Categorias Existentes', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Modulo', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Modulos', 'Manejo de Modulos', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Start', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('store', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cart', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('storeL', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('cartL', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Productos', 'Manejo de Inventario', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Producto', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('User', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Users', 'Manejo de Usuarios', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Roles', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Entregas', 'Manejo de Lugares de Entrega', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Entrega', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Checkout', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Manejos', 'Manejo de Horarios', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Manejo', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Historial', 'Mis Ordenes', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Ordenes', 'Manejo de Ordenes', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Orden', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Change', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlDscES`, `mdlDscEN`, `mdlState`, `mdlClass`) VALUES ('Directions', 'Mis Direcciones', ' ', 'ACT', 'MNU');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Approved', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('Canceled', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('forgot', 'ACT', 'PGE');
INSERT INTO `eCommerce`.`module` (`mdlCod`, `mdlState`, `mdlClass`) VALUES ('pwsd', 'ACT', 'PGE');

